import { Icon } from "react-native-elements";

export const PATIENTS = [
  {
    id: 0,
    appointedTime: "08:00 AM",
    appointedDate: "2020-10-26",
    name: "Andrew",
    image: require("../assets/man.png"),
    age: "30",
    gender: "Male",
    status: "Confirm",
    serialNo: 1,
    phoneNo: "+880 124 732 878",
    bloodGrp: "B+",
    onlineCons: "false",
    type: "New",
    emerg: "false",
  },
  {
    id: 1,
    appointedTime: "09:00 AM",
    appointedDate: "2020-10-28",
    name: "Lio",
    image: require("../assets/man.png"),
    age: "30",
    gender: "Male",
    status: "Pending",
    serialNo:2,
    phoneNo: "+880 124 732 878",
    bloodGrp: "B+",
    onlineCons: "false",
    type: "New",
    emerg: "false",
  },
  {
    id: 2,
    appointedTime: "10:00 PM",
    appointedDate: "2020-10-28",
    name: "Bella",
    image: require("../assets/man.png"),
    age: "20",
    gender: "Female",
    status: "Confirm",
    serialNo: 1,
    phoneNo: "+880 124 732 878",
    bloodGrp: "B+",
    onlineCons: "false",
    type: "New",
    emerg: "false",
  },
  {
    id: 3,
    appointedTime: "11:00 AM",
    appointedDate: "2020-10-31",
    name: "Alexa",
    image: require("../assets/man.png"),
    age: "30",
    gender: "Female",
    status: "Cancel",
    serialNo:2,
    phoneNo: "+880 124 732 878",
    bloodGrp: "B+",
    onlineCons: "false",
    type: "New",
    emerg: "false",
  },
  {
    id: 4,
    appointedTime: "12:50 PM",
    appointedDate: "2020-10-31",
    name: "Alex",
    image: require("../assets/man.png"),
    age: "30",
    gender: "Female",
    status: "Cancel",
    serialNo:1,
    phoneNo: "+880 124 732 878",
    bloodGrp: "B+",
    onlineCons: "false",
    type: "New",
    emerg: "false",
  },
  {
    id: 5,
    appointedTime: "10:00 PM",
    appointedDate: "2020-10-31",
    name: "Bella",
    image: require("../assets/man.png"),
    age: "20",
    gender: "Female",
    status: "Confirm",
    serialNo: 1,
    phoneNo: "+880 124 732 878",
    bloodGrp: "B+",
    onlineCons: "false",
    type: "New",
    emerg: "false",
  },{
    id: 6,
    appointedTime: "09:00 AM",
    appointedDate: "2020-11-01",
    name: "Lio",
    image: require("../assets/man.png"),
    age: "30",
    gender: "Male",
    status: "Pending",
    serialNo:2,
    phoneNo: "+880 124 732 878",
    bloodGrp: "B+",
    onlineCons: "false",
    type: "New",
    emerg: "false",
  },
  {
    id: 7,
    appointedTime: "10:00 PM",
    appointedDate: "2020-11-02",
    name: "Bella",
    image: require("../assets/man.png"),
    age: "20",
    gender: "Female",
    status: "Confirm",
    serialNo: 1,
    phoneNo: "+880 124 732 878",
    bloodGrp: "B+",
    onlineCons: "false",
    type: "New",
    emerg: "false",
  }
];
